# azurefrontend.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

# =========================
# BUILD
# =========================
- stage: Build
  jobs:
  - job: BuildJob

    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'
        displayName: 'Set up Node.js'

      - script: |
          npm ci
          npm run build
        displayName: 'npm install and build'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'dist'
          artifactName: 'frontend'
          publishLocation: 'Container'


# =========================
# DEPLOY
# =========================
- stage: Deploy
  dependsOn: Build

  jobs:
  - job: DeployJob

    steps:
      - download: current
        artifact: frontend

      - task: AzureStaticWebApp@0
        displayName: 'Deploy to Azure Static Web App'
        inputs:
          workingDirectory: '$(Pipeline.Workspace)'
          app_location: 'frontend'
          output_location: ''
          skip_app_build: true
          skip_api_build: true
          azure_static_web_apps_api_token: '$(deployment_token)'
